services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/dbpath
    environment:
      FLASK_APP: app.py
      DATABASE: "survey.db"
    command: flask run --host=0.0.0.0
